### ISSUE TITLE
Facilitate service lookup

### ISSUE THREAD

**Issue by maurerit** [chremoas/services-common#1]
Configuring service names and service namespaces along with linking services in the configuration is very burdensome.  Need to make the connection much less fluid by removing the ability for users to rename service names but allow them to rename service namespaces.

Given a configuration option of:

```
namespaces:
  service: com.aba-eve.srv
  command: com.aba-eve.cmd
  api: com.aba-eve.api
  web: com.aba-eve.web
```

We need the ability to be able to map services to these namespace types and then provide a mechanism where services can understand who lives where.

For instance: auth-srv is a service and will live in the service namespace.  We have a command 'role-cmd' that needs auth-srv data so instead of coding up that lookup inside each dependent service we provide a function:

```
func ServiceFullName(serviceName string, configuration *config.Configuration) string
```

Which would have access to a constant map of servceName => serviceNameSpaceType and be able to provide `com.aba-eve.srv.auth-srv` as a response.
